#include "HTMLPages.h"


/* Server Index Page */
char* OTAUpdatePage =
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
"<input type='file' name='update' id='file' onchange='sub(this)' style=display:none>"
"<label id='file-input' for='file'>   Choose file...</label>"
"<input type='submit' class=btn value='Update'>"
"<br><br>"
"<div id='prg'></div>"
"<br><div id='prgbar'><div id='bar'></div></div><br></form>"
"<script>"
"function sub(obj){"
"var fileName = obj.value.split('\\\\');"
"document.getElementById('file-input').innerHTML = '   '+ fileName[fileName.length-1];"
"};"
"$('form').submit(function(e){"
"e.preventDefault();"
"var form = $('#upload_form')[0];"
"var data = new FormData(form);"
"$.ajax({"
"url: '/update',"
"type: 'POST',"
"data: data,"
"contentType: false,"
"processData:false,"
"xhr: function() {"
"var xhr = new window.XMLHttpRequest();"
"xhr.upload.addEventListener('progress', function(evt) {"
"if (evt.lengthComputable) {"
"var per = evt.loaded / evt.total;"
"$('#prg').html('progress: ' + Math.round(per*100) + '%');"
"$('#bar').css('width',Math.round(per*100) + '%');"
"}"
"}, false);"
"return xhr;"
"},"
"success:function(d, s) {"
"console.log('success!') "
"},"
"error: function (a, b, c) {"
"}"
"});"
"});"
"</script>";




char* RegPage =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta name='viewport' content='width=device-width, initial-scale=1'>"
"<style>"
"body {"
    "font-family: Arial, Helvetica, sans-serif;"
"}"
"* {"
"    box-sizing: border-box;"
"}"
".container {"
"    padding: 16px;"
"    background-color: white;"
"    max-width: 600px;"
"    margin-left: auto;"
"    margin-right: auto;"
"    border: 2px solid black;"
"}"
"input[type=text], input[type=password] {"
"    width: 100%;"
"    padding: 15px;"
"    margin: 5px 0 22px 0;"
"    display: inline-block;"
"    border: none;"
"    background: #f1f1f1;"
"}"
"input[type=text]:focus, input[type=password]:focus {"
"    background-color: #ddd;"
"    outline: none;"
"}"
"hr {"
"    border: 1px solid #f1f1f1;"
"    margin-bottom: 25px;"
"}"
".registerbtn {"
"    background-color: #4CAF50;"
"    color: white;"
"    padding: 16px 20px;"
"    margin: 8px 0;"
"    border: none;"
"    cursor: pointer;"
"    width: 100%;"
"    opacity: 0.9;"
"}"
".registerbtn:hover {"
"    opacity: 1;"
"}"
"a {"
"    color: dodgerblue;"
"}"
".signin {"
"    background-color: #f1f1f1;"
"    text-align: center;"
"}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"  <form method='POST' action='#'>"
"    <h1>Register</h1>"
"    <p>Fill out the form to connect to the control unit.</p>"
"    <hr>"
"    <label><b>WIFI SSID</b></label>"
"    <input type='text' placeholder='Enter your SSID' name='ssid' required>"
"    <label for='psw'><b>Password</b></label>"
"    <input type='password' placeholder='Enter Password' name='psw' required>"
"    <button type='submit' class='registerbtn' id='submitbutton'>Submit</button>"
"  </form>"
"  <form method='POST' action='#'>"
"    <button type='submit' name='noreg' class='registerbtn' id='withoutreg' style='background-color:grey'>Continue without registration</button>"
"  </form>"
"  </div>"

"</body>"
"</html>";


char* HomePage = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta name='viewport' content='width=device-width, initial-scale=1'>"
"<style>"
"    h1{"
"        padding:10px;"
"        text-align: center;"
"    }"
".button {"
"  border-radius: 4px;"
"  background-color:  #4CAF50;"
"  border: none;"
"  color: #FFFFFF;"
"  text-align: center;"
"  font-size: 18px;"
"  padding: 20px;" 
"  width:100%;"
"  transition: all 0.5s;"
"  cursor: pointer;"
"  margin: 5px;"
"}"
".container {"
"    padding: 16px;"
"    background-color: white;"
"    max-width: 600px;"
"    margin-left: auto;"
"    margin-right: auto;"
"    border: 2px solid black;"
"    margin-top: auto;"
"    margin-bottom: auto; } "          
".button span {"
"  cursor: pointer;"
"  display: inline-block;"
"  position: relative;"
"  transition: 0.5s;"
"}"
".button span:after {"
"  content: '\\25B6';"
"  position: absolute;"
"  opacity: 0;"
"  top: 0;"
"  right: -20px;"
"  transition: 0.5s;"
"}"
".button:hover span {"
"  padding-right: 25px;"
"}"
".button:hover span:after {"
"  opacity: 1;"
"  right: 0;"
"}"
"</style>"
"</head>"
"<body>"
"<div class = 'container'>"
"    <h1>Main menu</h1>"
"<form action='/addUser' method='get'>"
"    <button class='button'><span>Add user</span></button>"
"</form>"
"    <hr>"
"<form action='/deleteUser' method='get'>"
"    <button class='button'><span>Delete user </span></button>"
"</form>"
"    <hr>"
"    <button class='button'><span>User list </span></button>"
"    <hr>"
"    <button class='button' style='background-color: grey';><span>Wifi setup </span></button>"
"</div>"
"</body>"
"</html>";


char* DeleteUserPage = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta name='viewport' content='width=device-width, initial-scale=1'>"
"<style>"
"body {"
"    font-family: Arial, Helvetica, sans-serif;"
"}"
"* {"
"    box-sizing: border-box;"
"}"
".container {"
"    padding: 16px;"
"    background-color: white;"
"    max-width: 600px;"
"    margin-left: auto;"
"    margin-right: auto;"
"    border: 2px solid black;"
"}"
"input[type=text], input[type=password] {"
"    width: 100%;"
"    padding: 15px;"
"    margin: 5px 0 22px 0;"
"    display: inline-block;"
"    border: none;"
"   background: #f1f1f1;"
"}"
"input[type=text]:focus, input[type=password]:focus {"
"    background-color: #ddd;"
"    outline: none;"
"}"
"hr {"
"    border: 1px solid #f1f1f1;"
"    margin-bottom: 25px;"
"}"
".registerbtn {"
"    background-color: #4CAF50;"
"    color: white;"
"    padding: 16px 20px;"
"    margin: 8px 0;"
"    border: none;"
"    cursor: pointer;"
"    width: 100%;"
"    opacity: 0.9;"
"}"
".registerbtn:hover {"
"    opacity: 1;"
"}"
"a {"
"    color: dodgerblue;"
"}"
".signin {"
"    background-color: #f1f1f1;"
"    text-align: center;"
"}"
"</style>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h1>Delete user by id</h1>"
"    <hr>"
"<form method='post' action='#'>"
"    <label><b>USER id</b></label>"
"    <input type='text' placeholder='Enter user id' name='delUsrId' required>"
"    <button type='submit' name='delUsrBtn'>Delete user </button>"
"  </div>"
"</form>"
"</body>"
"</html>";













char* AddUserPage =
"<!DOCTYPE html>"
"<html>"
"<style>"
"body {font-family: Arial, Helvetica, sans-serif;}"
"* {box-sizing: border-box}"
"input[type=text], input[type=password] {"
"  width: 100%;"
"  padding: 15px;"
"  margin: 5px 0 22px 0;"
"  display: inline-block;"
"  border: none;"
"  background: #f1f1f1;"
"}"
"input[type=text]:focus, input[type=password]:focus {"
"  background-color: #ddd;"
"  outline: none;"
"}"
"hr {"
"  border: 1px solid #f1f1f1;"
"  margin-bottom: 25px;"
"}"
"button {"
"  background-color: #4CAF50;"
"  color: white;"
"  padding: 14px 20px;"
"  margin: 8px 0;"
"  border: none;"
"  cursor: pointer;"
"  width: 100%;"
"  opacity: 0.9;"
"}"
"button:hover {"
"  opacity:1;"
"}"
".cancelbtn {"
"  padding: 14px 20px;"
"  background-color: #f44336;"
"}"
".cancelbtn, .signupbtn {"
"  float: left;"
"  width: 50%;"
"}"
".container {"
"  padding: 16px;"
"}"
".clearfix::after {"
"  content: "";"
"  clear: both;"
"  display: table;"
"}"
"@media screen and (max-width: 300px) {"
"  .cancelbtn, .signupbtn {"
"     width: 100%;"
"  }"
"}"
"</style>"
"<body>"
"    <form method='POST' action='#' style='border:1px solid #ccc ;max-width: 600px; margin-left: auto; margin-right: auto;'>"
"  <div class='container'>"
"    <h1>Register a new fingerprint</h1>"
"    <p>Please fill in this form to sign up new user</p>"
"    <hr>"
"    <label for='userId'><b>Enter User id</b></label>"
"    <input type='text' placeholder='User id' name='usrId' required>"
"    <label for='name'><b>Enter User Name</b></label>"
"    <input type='text' placeholder='User Name' name='usrName' required>"
"    <label for='status'><b>Enter User status</b></label>"
"    <input type='text' placeholder='User Status' name='usrStatus' required>"
"    <label for='key'><b>Enter Unique key</b></label>"
"    <input type='text' placeholder='Key' name='usrKey' required>"
"    <div class='clearfix'>"
"      <button type='button' class='cancelbtn'>Cancel</button>"
"      <button type='submit' class='signupbtn'>Sign Up</button>"
"    </div>"
"  </div>"
"</form>"
"</body>"
"</html>";
